name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Csound (Ubuntu)
        if: runner.os == 'Linux'
        run: apt-get install csound

      - name: Install Csound (macOS)
        if: runner.os == 'macOS'
        run: brew install csound

      # - name: Install Csound (Windows)
        # if: runner.os == 'Window'
        # run: choco install -y csound

      # - name: Install LLVM on Windows
        # if: runner.os == 'Windows'
        # run: choco install -y llvm
        # run: echo "::add-path::C:\\msys64\\mingw64\\bin"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      # - uses: davidB/rust-cargo-make@v1
      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
