name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Csound (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install libcsound64-dev

      - name: Install Csound (macOS)
        if: runner.os == 'macOS'
        run: brew install csound

      - name: Cache Csound (Ubuntu)
        uses: actions/cache@v2
        if: runner.os == 'Linux'
        with: 
          path: /usr/lib/libcsound64.so
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('/usr/lib/libcsound64.so') }}

      - name: Cache Csound (macOS)
        uses: actions/cache@v2
        if: runner.os == 'macOS'
        with: 
          path: /usr/local/Cellar/csound
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('/usr/local/Cellar/csound/6.15.0_4/Frameworks/CsoundLib64.framework/CsoundLib64') }}

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
